// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbDct4qwUSRrh7iNsKZGqNLDq4RfKnj3g',
    appId: '1:900525605268:web:b5e00be69d67fc1fd7cf81',
    messagingSenderId: '900525605268',
    projectId: 'k53-simulator',
    authDomain: 'k53-simulator.firebaseapp.com',
    storageBucket: 'k53-simulator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTkQhqT_EFGVyCFrFtFekm5FSLsz6kYyU',
    appId: '1:900525605268:ios:990379e9cfc4ef03d7cf81',
    messagingSenderId: '900525605268',
    projectId: 'k53-simulator',
    storageBucket: 'k53-simulator.firebasestorage.app',
    iosBundleId: 'com.example.k53Simulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTkQhqT_EFGVyCFrFtFekm5FSLsz6kYyU',
    appId: '1:900525605268:ios:990379e9cfc4ef03d7cf81',
    messagingSenderId: '900525605268',
    projectId: 'k53-simulator',
    storageBucket: 'k53-simulator.firebasestorage.app',
    iosBundleId: 'com.example.k53Simulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbDct4qwUSRrh7iNsKZGqNLDq4RfKnj3g',
    appId: '1:900525605268:web:06b857cce3e02763d7cf81',
    messagingSenderId: '900525605268',
    projectId: 'k53-simulator',
    authDomain: 'k53-simulator.firebaseapp.com',
    storageBucket: 'k53-simulator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1B_oUVXi6F1ALW0rrhlPojtXqJcOD1m0',
    appId: '1:900525605268:android:442514495ed9c4c8d7cf81',
    messagingSenderId: '900525605268',
    projectId: 'k53-simulator',
    storageBucket: 'k53-simulator.firebasestorage.app',
  );

}